<?php

return [
    'workplaces' => [
        'general_admin' => 'الإدارة العامة',
        'ajdabiya' => 'إجدابيا',
        'al_jabal_al_akhdar' => 'الجبل الأخضر',
        'al_jufra' => 'الجفرة',
        'al_jafara' => 'الجفارة',
        'al_hizam_al_akhdar' => 'الحزام الأخضر',
        'al_zawiya' => 'الزاوية',
        'al_shati' => 'الشاطئ',
        'al_ajaylat' => 'العجيلات',
        'al_qubba' => 'القبة',
        'al_kufra' => 'الكفرة',
        'al_marj' => 'المرج',
        'al_murqub' => 'المرقب',
        'al_wahat' => 'الواحات',
        'benghazi' => 'بنغازي',
        'bani_walid' => 'بني وليد',
        'tajoura' => 'تاجوراء',
        'tarhuna_msallata' => 'ترهونة ومسلاته',
        'derna' => 'درنة',
        'zuwara' => 'زوارة',
        'sebha' => 'سبها',
        'sirte' => 'سرت',
        'sabratha' => 'صبراته',
        'sorman' => 'صرمان',
        'tobuk' => 'طبرق',
        'tripoli' => 'طرابلس',
        'ghat' => 'غات',
        'ghadames' => 'غدامس',
        'gharyan' => 'غريان',
        'qasr_bin_ghashir' => 'قصر بن غشير',
        'marada' => 'مرادة',
        'murzuq' => 'مرزق',
        'mizda' => 'مزدة',
        'misrata' => 'مصراته',
        'nalut' => 'نالوت',
        'wadi_al_hayat' => 'وادي الحياة',
        'yafran' => 'يفرن',
        'janzour' => 'جنزور',
        'gulf_of_sidra' => 'خليج السدرة',
        'zliten' => 'زليتن',
        'large_taxpayers_tripoli' => 'كبار الممولين طرابلس',
    ],

    'job_titles' => [
        'board_chair' => 'رئيس مجلس إدارة',
        'general_manager' => 'مدير عام',
        'department_manager' => 'مدير إدارة',
        'assistant_department_manager' => 'مساعد مدير إدارة',
        'deputy_department_manager' => 'نائب مدير إدارة',
        'section_head' => 'رئيس قسم',
        'deputy_section_head' => 'نائب رئيس قسم',
        'assistant_section_head' => 'مساعد رئيس قسم',
        'collaborator' => 'متعاون',
        'employee' => 'موظف',
        'other' => 'مسمى آخر',
    ],

    'cities' => [
        'ajdabiya' => 'إجدابيا',
        'al_jabal_al_akhdar' => 'الجبل الأخضر',
        'al_jufra' => 'الجفرة',
        'al_jafara' => 'الجفارة',
        'al_hizam_al_akhdar' => 'الحزام الأخضر',
        'al_zawiya' => 'الزاوية',
        'al_shati' => 'الشاطئ',
        'al_ajaylat' => 'العجيلات',
        'al_qubba' => 'القبة',
        'al_kufra' => 'الكفرة',
        'al_marj' => 'المرج',
        'al_murqub' => 'المرقب',
        'al_wahat' => 'الواحات',
        'benghazi' => 'بنغازي',
        'bani_walid' => 'بني وليد',
        'tajoura' => 'تاجوراء',
        'tarhuna_msallata' => 'ترهونة ومسلاته',
        'derna' => 'درنة',
        'zuwara' => 'زوارة',
        'sebha' => 'سبها',
        'sirte' => 'سرت',
        'sabratha' => 'صبراته',
        'sorman' => 'صرمان',
        'tobuk' => 'طبرق',
        'tripoli' => 'طرابلس',
        'ghat' => 'غات',
        'ghadames' => 'غدامس',
        'gharyan' => 'غريان',
        'qasr_bin_ghashir' => 'قصر بن غشير',
        'marada' => 'مرادة',
        'murzuq' => 'مرزق',
        'mizda' => 'مزدة',
        'misrata' => 'مصراته',
        'nalut' => 'نالوت',
        'wadi_al_hayat' => 'وادي الحياة',
        'yafran' => 'يفرن',
        'janzour' => 'جنزور',
        'gulf_of_sidra' => 'خليج السدرة',
        'zliten' => 'زليتن',
    ],

    /*
    | Phone scans of ورقة العائلة are often well above PHP/Livewire defaults.
    | Sizes are kilobytes (Laravel file validation / Livewire temp uploads).
    */
    'uploads' => [
        'max_kilobytes' => (int) env('REGISTRATION_UPLOAD_MAX_KB', 51200),
        'family_mimes' => ['pdf', 'jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'],
        'photo_mimes' => ['jpg', 'jpeg', 'png', 'webp'],
    ],

    'chronic_conditions' => [
        'diabetes' => 'السكري',
        'hypertension' => 'ارتفاع ضغط الدم',
        'heart_disease' => 'أمراض القلب و الشرايين',
        'asthma' => 'الربو',
        'copd' => 'الانسداد الرئوي',
        'kidney_failure' => 'أمراض الكلى المزمنة',
        'cancer' => 'السرطان',
        'arthritis' => 'أمراض المفاصل المزمنة',
        'chronic_neurological' => 'الأمراض العصبية المزمنة',
        'chronic_autoimmune' => 'الأمراض المناعية المزمنة',
        'alzheimers' => 'الزهايمر',
        'epilepsy' => 'الصرع',
        'hepatitis' => 'التهاب الكبد المزمن',
        'osteoporosis' => 'هشاشة العظام',
    ],
];
