<?php

return [
    'workplaces' => [
        'general_admin' => 'الإدارة العامة',
        'al_asabaa' => 'الاصابعة',
        'al_jufra' => 'الجفرة',
        'al_jamil' => 'الجميل',
        'al_zawiya' => 'الزاوية',
        'al_zintan' => 'الزنتان',
        'al_ajaylat' => 'العجيلات',
        'al_murqub' => 'المرقب',
        'batin_al_jabal' => 'باطن الجبل',
        'tarhuna' => 'ترهونة',
        'jado' => 'جادو',
        'zliten' => 'زليتن',
        'zuwara' => 'زوارة',
        'sebha' => 'سبها',
        'sabratha_sorman' => 'صبراته / صرمان',
        'tripoli' => 'طرابلس',
        'ghat' => 'غات',
        'ghadames' => 'غدامس',
        'southwest_tripoli' => 'غرب جنوب طرابلس',
        'gharyan' => 'غريان',
        'bani_walid' => 'فرع بني وليد',
        'murzuq' => 'مرزق',
        'mizda' => 'مزدة',
        'msallata' => 'مسلاته',
        'misrata' => 'مصراته',
        'nalut' => 'نالوت',
        'wadi_al_shati' => 'وادى الشاطئ',
        'wadi_al_ajal' => 'وادي الاجال',
    ],

    'job_titles' => [
        'board_chair' => 'رئيس مجلس إدارة',
        'general_manager' => 'مدير عام',
        'department_manager' => 'مدير إدارة',
        'assistant_department_manager' => 'مساعد مدير إدارة',
        'deputy_department_manager' => 'نائب مدير إدارة',
        'section_head' => 'رئيس قسم',
        'deputy_section_head' => 'نائب رئيس قسم',
        'assistant_section_head' => 'مساعد رئيس قسم',
        'collaborator' => 'متعاون',
        'employee' => 'موظف',
        'other' => 'مسمى آخر',
    ],

    'cities' => [
        'al_asabaa' => 'الاصابعة',
        'al_jufra' => 'الجفرة',
        'al_jamil' => 'الجميل',
        'al_zawiya' => 'الزاوية',
        'al_zintan' => 'الزنتان',
        'al_ajaylat' => 'العجيلات',
        'al_murqub' => 'المرقب',
        'batin_al_jabal' => 'باطن الجبل',
        'tarhuna' => 'ترهونة',
        'jado' => 'جادو',
        'zliten' => 'زليتن',
        'zuwara' => 'زوارة',
        'sebha' => 'سبها',
        'sabratha_sorman' => 'صبراته / صرمان',
        'tripoli' => 'طرابلس',
        'ghat' => 'غات',
        'ghadames' => 'غدامس',
        'southwest_tripoli' => 'غرب جنوب طرابلس',
        'gharyan' => 'غريان',
        'bani_walid' => 'فرع بني وليد',
        'murzuq' => 'مرزق',
        'mizda' => 'مزدة',
        'msallata' => 'مسلاته',
        'misrata' => 'مصراته',
        'nalut' => 'نالوت',
        'wadi_al_shati' => 'وادى الشاطئ',
        'wadi_al_ajal' => 'وادي الاجال',
    ],

    'chronic_conditions' => [
        'heart_disease' => 'أمراض القلب',
        'cancer' => 'السرطان',
        'arthritis' => 'التهاب المفاصل المزمن',
        'kidney_failure' => 'الفشل الكلوي المزمن',
        'copd' => 'مرض الانسداد الرئوي المزمن',
        'alzheimers' => 'الزهايمر',
        'epilepsy' => 'الصرع',
        'hepatitis' => 'التهاب الكبد المزمن',
        'osteoporosis' => 'هشاشة العظام',
    ],
];
