<?php

return [
    'workplaces' => [
        'general_admin' => 'الإدارة العامة',
        'ajdabiya' => 'إجدابيا',
        'al_jabal_al_akhdar' => 'الجبل الأخضر',
        'al_jufra' => 'الجفرة',
        'al_jafara' => 'الجفارة',
        'al_hizam_al_akhdar' => 'الحزام الأخضر',
        'al_zawiya' => 'الزاوية',
        'al_shati' => 'الشاطئ',
        'al_ajaylat' => 'العجيلات',
        'al_qubba' => 'القبة',
        'al_kufra' => 'الكفرة',
        'al_marj' => 'المرج',
        'al_murqub' => 'المرقب',
        'al_wahat' => 'الواحات',
        'benghazi' => 'بنغازي',
        'bani_walid' => 'بني وليد',
        'tajoura' => 'تاجوراء',
        'tarhuna_msallata' => 'ترهونة ومسلاته',
        'derna' => 'درنة',
        'zuwara' => 'زوارة',
        'sebha' => 'سبها',
        'sirte' => 'سرت',
        'sabratha' => 'صبراته',
        'sorman' => 'صرمان',
        'tobuk' => 'طبرق',
        'tripoli' => 'طرابلس',
        'ghat' => 'غات',
        'ghadames' => 'غدامس',
        'gharyan' => 'غريان',
        'qasr_bin_ghashir' => 'قصر بن غشير',
        'marada' => 'مرادة',
        'murzuq' => 'مرزق',
        'mizda' => 'مزدة',
        'misrata' => 'مصراته',
        'nalut' => 'نالوت',
        'wadi_al_hayat' => 'وادي الحياة',
        'yafran' => 'يفرن',
        'janzour' => 'جنزور',
        'gulf_of_sidra' => 'خليج السدرة',
        'zliten' => 'زليتن',
        'large_taxpayers_tripoli' => 'كبار الممولين طرابلس',
    ],

    'job_titles' => [
        'board_chair' => 'رئيس مجلس إدارة',
        'general_manager' => 'مدير عام',
        'department_manager' => 'مدير إدارة',
        'assistant_department_manager' => 'مساعد مدير إدارة',
        'deputy_department_manager' => 'نائب مدير إدارة',
        'section_head' => 'رئيس قسم',
        'deputy_section_head' => 'نائب رئيس قسم',
        'assistant_section_head' => 'مساعد رئيس قسم',
        'collaborator' => 'متعاون',
        'employee' => 'موظف',
        'other' => 'مسمى آخر',
    ],

    'cities' => [
        'ajdabiya' => 'إجدابيا',
        'al_jabal_al_akhdar' => 'الجبل الأخضر',
        'al_jufra' => 'الجفرة',
        'al_jafara' => 'الجفارة',
        'al_hizam_al_akhdar' => 'الحزام الأخضر',
        'al_zawiya' => 'الزاوية',
        'al_shati' => 'الشاطئ',
        'al_ajaylat' => 'العجيلات',
        'al_qubba' => 'القبة',
        'al_kufra' => 'الكفرة',
        'al_marj' => 'المرج',
        'al_murqub' => 'المرقب',
        'al_wahat' => 'الواحات',
        'benghazi' => 'بنغازي',
        'bani_walid' => 'بني وليد',
        'tajoura' => 'تاجوراء',
        'tarhuna_msallata' => 'ترهونة ومسلاته',
        'derna' => 'درنة',
        'zuwara' => 'زوارة',
        'sebha' => 'سبها',
        'sirte' => 'سرت',
        'sabratha' => 'صبراته',
        'sorman' => 'صرمان',
        'tobuk' => 'طبرق',
        'tripoli' => 'طرابلس',
        'ghat' => 'غات',
        'ghadames' => 'غدامس',
        'gharyan' => 'غريان',
        'qasr_bin_ghashir' => 'قصر بن غشير',
        'marada' => 'مرادة',
        'murzuq' => 'مرزق',
        'mizda' => 'مزدة',
        'misrata' => 'مصراته',
        'nalut' => 'نالوت',
        'wadi_al_hayat' => 'وادي الحياة',
        'yafran' => 'يفرن',
        'janzour' => 'جنزور',
        'gulf_of_sidra' => 'خليج السدرة',
        'zliten' => 'زليتن',
    ],

    /*
    | Phone scans of ورقة العائلة are often well above PHP/Livewire defaults.
    | Sizes are kilobytes (Laravel file validation / Livewire temp uploads).
    */
    'uploads' => [
        'max_kilobytes' => (int) env('REGISTRATION_UPLOAD_MAX_KB', 51200),
        'family_mimes' => ['pdf', 'jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'],
        'photo_mimes' => ['jpg', 'jpeg', 'png', 'webp'],
    ],

    /*
    | Nationalities available when spouse/mother is not Libyan.
    | Libya itself is selected via the "ليبي؟" toggle, not this list.
    |
    | nationality_priority: shown first (neighbors / common in Libya), then A–Z, then أخرى.
    */
    'nationality_priority' => [
        'egyptian',
        'tunisian',
        'algerian',
        'moroccan',
        'sudanese',
        'chadian',
        'nigerien',
        'palestinian',
        'syrian',
        'lebanese',
        'jordanian',
        'saudi',
        'emirati',
        'kuwaiti',
        'qatari',
        'bahraini',
        'omani',
        'yemeni',
        'iraqi',
        'turkish',
        'eritrean',
        'somali',
        'ethiopian',
    ],

    'nationalities' => [
        'afghan' => 'أفغانستان',
        'albanian' => 'ألبانيا',
        'algerian' => 'الجزائر',
        'american' => 'الولايات المتحدة',
        'argentine' => 'الأرجنتين',
        'armenian' => 'أرمينيا',
        'australian' => 'أستراليا',
        'austrian' => 'النمسا',
        'azerbaijani' => 'أذربيجان',
        'bahraini' => 'البحرين',
        'bangladeshi' => 'بنغلاديش',
        'belarusian' => 'بيلاروسيا',
        'belgian' => 'بلجيكا',
        'beninese' => 'بنين',
        'bosnian' => 'البوسنة والهرسك',
        'brazilian' => 'البرازيل',
        'british' => 'المملكة المتحدة',
        'bulgarian' => 'بلغاريا',
        'burkinabe' => 'بوركينا فاسو',
        'cameroonian' => 'الكاميرون',
        'canadian' => 'كندا',
        'chadian' => 'تشاد',
        'chinese' => 'الصين',
        'comorian' => 'جزر القمر',
        'congolese' => 'الكونغو',
        'croatian' => 'كرواتيا',
        'cypriot' => 'قبرص',
        'czech' => 'التشيك',
        'danish' => 'الدنمارك',
        'djiboutian' => 'جيبوتي',
        'dutch' => 'هولندا',
        'egyptian' => 'مصر',
        'emirati' => 'الإمارات',
        'eritrean' => 'إريتريا',
        'estonian' => 'إستونيا',
        'ethiopian' => 'إثيوبيا',
        'filipino' => 'الفلبين',
        'finnish' => 'فنلندا',
        'french' => 'فرنسا',
        'gabonese' => 'الغابون',
        'gambian' => 'غامبيا',
        'georgian' => 'جورجيا',
        'german' => 'ألمانيا',
        'ghanaian' => 'غانا',
        'greek' => 'اليونان',
        'guinean' => 'غينيا',
        'hungarian' => 'المجر',
        'icelandic' => 'آيسلندا',
        'indian' => 'الهند',
        'indonesian' => 'إندونيسيا',
        'iranian' => 'إيران',
        'iraqi' => 'العراق',
        'irish' => 'أيرلندا',
        'italian' => 'إيطاليا',
        'ivorian' => 'ساحل العاج',
        'japanese' => 'اليابان',
        'jordanian' => 'الأردن',
        'kazakh' => 'كازاخستان',
        'kenyan' => 'كينيا',
        'korean' => 'كوريا الجنوبية',
        'kuwaiti' => 'الكويت',
        'kyrgyz' => 'قيرغيزستان',
        'latvian' => 'لاتفيا',
        'lebanese' => 'لبنان',
        'lithuanian' => 'ليتوانيا',
        'luxembourgish' => 'لوكسمبورغ',
        'malaysian' => 'ماليزيا',
        'malian' => 'مالي',
        'maltese' => 'مالطا',
        'mauritanian' => 'موريتانيا',
        'mexican' => 'المكسيك',
        'moldovan' => 'مولدوفا',
        'montenegrin' => 'الجبل الأسود',
        'moroccan' => 'المغرب',
        'nigerian' => 'نيجيريا',
        'nigerien' => 'النيجر',
        'norwegian' => 'النرويج',
        'omani' => 'عُمان',
        'pakistani' => 'باكستان',
        'palestinian' => 'فلسطين',
        'polish' => 'بولندا',
        'portuguese' => 'البرتغال',
        'qatari' => 'قطر',
        'romanian' => 'رومانيا',
        'russian' => 'روسيا',
        'rwandan' => 'رواندا',
        'saudi' => 'السعودية',
        'senegalese' => 'السنغال',
        'serbian' => 'صربيا',
        'singaporean' => 'سنغافورة',
        'slovak' => 'سلوفاكيا',
        'slovenian' => 'سلوفينيا',
        'somali' => 'الصومال',
        'south_african' => 'جنوب أفريقيا',
        'spanish' => 'إسبانيا',
        'sri_lankan' => 'سريلانكا',
        'sudanese' => 'السودان',
        'swedish' => 'السويد',
        'swiss' => 'سويسرا',
        'syrian' => 'سوريا',
        'tajik' => 'طاجيكستان',
        'tanzanian' => 'تنزانيا',
        'thai' => 'تايلاند',
        'togolese' => 'توغو',
        'tunisian' => 'تونس',
        'turkish' => 'تركيا',
        'turkmen' => 'تركمانستان',
        'ugandan' => 'أوغندا',
        'ukrainian' => 'أوكرانيا',
        'uzbek' => 'أوزبكستان',
        'venezuelan' => 'فنزويلا',
        'vietnamese' => 'فيتنام',
        'yemeni' => 'اليمن',
        'other' => 'أخرى',
    ],

    'chronic_conditions' => [
        'diabetes' => 'السكري',
        'hypertension' => 'ارتفاع ضغط الدم',
        'heart_disease' => 'أمراض القلب و الشرايين',
        'asthma' => 'الربو',
        'copd' => 'الانسداد الرئوي',
        'kidney_failure' => 'أمراض الكلى المزمنة',
        'cancer' => 'السرطان',
        'arthritis' => 'أمراض المفاصل المزمنة',
        'chronic_neurological' => 'الأمراض العصبية المزمنة',
        'chronic_autoimmune' => 'الأمراض المناعية المزمنة',
        'alzheimers' => 'الزهايمر',
        'epilepsy' => 'الصرع',
        'hepatitis' => 'التهاب الكبد المزمن',
        'osteoporosis' => 'هشاشة العظام',
    ],
];
